package com.loopermallee.moncchichi.telemetry

/**
 * Represents a telemetry log event generated by the app ↔ device BLE system.
 * Used by Live Log, diagnostics, and export features.
 */
data class G1TelemetryEvent(
    val source: String,          // e.g. "APP", "SERVICE", "DEVICE"
    val tag: String,             // e.g. "[BLE]", "[BATTERY]", "[NOTIFY]"
    val message: String,         // human-readable message
    val timestamp: Long = System.currentTimeMillis()
) {
    override fun toString(): String {
        val time = java.text.SimpleDateFormat("HH:mm:ss.SSS", java.util.Locale.getDefault())
            .format(java.util.Date(timestamp))
        return "[$time][$source][$tag] $message"
    }
}
