package com.loopermallee.moncchichi.telemetry

/**
 * Represents a telemetry log event generated by the app or device.
 * Used for Live Log, BLE diagnostics, and session export.
 */
data class G1TelemetryEvent(
    val source: String,          // e.g. "APP", "DEVICE", "SERVICE"
    val tag: String,             // e.g. "[NOTIFY]", "[BATTERY]", "[EXPORT]"
    val message: String,         // human-readable message
    val timestamp: Long = System.currentTimeMillis() // event time in ms
) {
    override fun toString(): String {
        val time = java.text.SimpleDateFormat("HH:mm:ss.SSS")
            .format(java.util.Date(timestamp))
        return "[$time][$source][$tag] $message"
    }
}
